services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    restart: unless-stopped
    ports:
      - "2283:2283"
    environment:
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - REDIS_HOSTNAME=redis
    env_file: .env
    volumes:
      - ./volumes/upload:/usr/src/app/upload
    depends_on:
      - redis

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./volumes/model-cache:/cache

  redis:
    image: docker.io/valkey/valkey:8-bookworm
    restart: unless-stopped
    volumes:
      - ./volumes/redis:/data
